//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hasta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hasta()
        {
            this.randevu = new HashSet<randevu>();
        }
    
        public int hastaNo { get; set; }
        public string hastaTcNo { get; set; }
        public string hastaAdi { get; set; }
        public string hastoSoyadi { get; set; }
        public string hastaTel { get; set; }
        public string hastaCinsiyet { get; set; }
        public string hastaDogumYeri { get; set; }
        public string hastaAnneAdi { get; set; }
        public string hastaBabaAdi { get; set; }
        public string hastaAdres { get; set; }
        public string hastaKanGrubu { get; set; }
        public string hastaMedeniHali { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<randevu> randevu { get; set; }
    }
}
