//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilac
    {
        public int ilacNo { get; set; }
        public string ilacAdı { get; set; }
        public Nullable<int> ilacTuruNo { get; set; }
    
        public virtual ilacTuru ilacTuru { get; set; }
    }
}
