//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int KullaniciID { get; set; }
        public int KisiId { get; set; }
        public Nullable<int> RolId { get; set; }
        public string KullaniciAd { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> doktorNo { get; set; }
    
        public virtual Kisi Kisi { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
