//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GorselEntities1 : DbContext
    {
        public GorselEntities1()
            : base("name=GorselEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<doktor> doktor { get; set; }
        public virtual DbSet<Hasta> Hasta { get; set; }
        public virtual DbSet<ilac> ilac { get; set; }
        public virtual DbSet<ilacTuru> ilacTuru { get; set; }
        public virtual DbSet<Kisi> Kisi { get; set; }
        public virtual DbSet<klinik> klinik { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<randevu> randevu { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Sonislemhasta> Sonislemhasta { get; set; }
        public virtual DbSet<sonSecimHasta> sonSecimHasta { get; set; }
    }
}
