//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class randevu
    {
        public int randevuId { get; set; }
        public string randevuSaat { get; set; }
        public string randevuTarih { get; set; }
        public string randevuKlinik { get; set; }
        public Nullable<int> hastaNo { get; set; }
        public Nullable<int> doktorNo { get; set; }
    
        public virtual doktor doktor { get; set; }
        public virtual Hasta Hasta { get; set; }
    }
}
