//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sonislemhasta
    {
        public int hastaSSSNo { get; set; }
        public string hastaAdss { get; set; }
        public string hastaSoyadss { get; set; }
        public string hastaTcNo { get; set; }
        public string hastaSikayetss { get; set; }
        public string hastailacss { get; set; }
        public string hastaislemss { get; set; }
    }
}
