//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sonSecimHasta
    {
        public int ssHastaNo { get; set; }
        public int hastaNoS { get; set; }
        public string hastaAdS { get; set; }
        public string hastaSoyadS { get; set; }
        public string doktorAdS { get; set; }
        public Nullable<int> doktorNoS { get; set; }
        public string hastaSikayetS { get; set; }
    }
}
